# Generated by Django 4.0 on 2022-02-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewed',
            name='Rating',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=1),
        ),
    ]
